### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by giannik** [karl-sjogren/letter-avatar-service#2]
After downloading and trying this out , I cant get to build it and tests fail.
Must be because of imagesharp changes .
Any chance this can be fixed?
I upgraded imagesharp to latest nuget versions,so seems there are breaking changes.
Thanks

**Comment by karl-sjogren** [comment]
Yeah this won't work with the latest imagesharp right now. I'll look into updating it as soon as possible.

**Comment by karl-sjogren** [comment]
New versions of the nuget packages have been released based on the latest imagesharp.

https://www.nuget.org/packages/LetterAvatars.AspNetCore/2.0.0
https://www.nuget.org/packages/LetterAvatars.Generator/2.0.0
